[build]
  publish = "public"
  functions = "netlify/functions"

[functions.environment]
  API_KEY = "your_superparser_api_key"

[[redirects]]
  from = "/parse-resume"
  to = "/.netlify/functions/parse-resume"
  status = 200
